### ISSUE TITLE
Logout()

### ISSUE THREAD

**Issue by Wortak** [yuri-moens/laravel-ldap-auth#5]
i receive an error when i use the logout() method.

![logout](https://cloud.githubusercontent.com/assets/7986405/3393440/719475fa-fcc5-11e3-9dae-6543c6e561dd.jpg)

**Comment by yuri-moens** [comment]
Added a check for GenericUsers so it shouldn't throw an error anymore.

**Comment by Wortak** [comment]
Thank you for you modul, exactly what I'm looking for.
