### ISSUE TITLE
php 5.4 or above required

### ISSUE THREAD

**Issue by sitzmar** [yuri-moens/laravel-ldap-auth#6]
The bracket [ ] array notation used in a couple of places requires php 5.4 or greater. If there are no other dependencies on 5.4 it would be nice to open this up for users on 5.3

At the very least, a note in the readme would be appreciated.

Thanks!

**Comment by yuri-moens** [comment]
Seeing as there is nothing else that requires 5.4 I changed the notation to the older one. Unless I missed some it should now work on 5.3 again.

**Comment by sitzmar** [comment]
Works great now, thank you!
