### ISSUE TITLE
OpendLDAP uniqueness of attribute

### ISSUE THREAD

**Issue by akash3456** [yuri-moens/laravel-ldap-auth#8]
How do I change the uniqueness of an attribute in openLDAP and phpldapadmin? I always get the following message:

Warning: ldap_mod_add(): Modify: Type or value exists in /var/www/html/Cou.php on line 40

**Comment by yuri-moens** [comment]
This is a Laravel 5 package for suppporting authentication against OpenLDAP. I think your question should be asked to the people behind phpLDAPAdmin. If you do have an issue with this package, try rephrasing it because I misunderstood.
